### ISSUE TITLE
can it run with iphone and wifi router?

### ISSUE THREAD

**Issue by csrgxtu** [mushfiq/rssi-system#29]
i want to implement the rssi positioning demo with iphone and wifi router, what is the procedure?

* a rest server that can receive rssi signal data from iphone and do the matching

* a iphone client that can send the rssi data to the server, and display the result on map

* a wifi router location database

is that right?

**Comment by mushfiq** [comment]
If your server can do the calculation, should be fine. Not sure how wifi can come in to the game though. Check out project summary where we described our approach.
